/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Men' : null } |
  { 'Accessories' : null } |
  { 'Kids' : null } |
  { 'Women' : null };
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'guestEmail' : [] | [string],
  'updatedAt' : Timestamp,
  'userPrincipal' : [] | [Principal],
  'totalAmount' : bigint,
  'shippingAddress' : ShippingAddress,
  'items' : Array<OrderItem>,
  'stripeSessionId' : [] | [string],
}
export type OrderId = bigint;
export interface OrderInput {
  'guestEmail' : [] | [string],
  'shippingAddress' : ShippingAddress,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'color' : string,
  'size' : string,
  'productId' : ProductId,
  'quantity' : bigint,
  'priceAtPurchase' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : ProductId,
  'imageRefs' : Array<string>,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'sizes' : Array<string>,
  'updatedAt' : Timestamp,
  'category' : Category,
  'colors' : Array<string>,
  'price' : bigint,
  'careInstructions' : string,
}
export interface ProductFilter {
  'color' : [] | [string],
  'size' : [] | [string],
  'maxPrice' : [] | [bigint],
  'searchTerm' : [] | [string],
  'category' : [] | [Category],
  'minPrice' : [] | [bigint],
}
export type ProductId = bigint;
export interface ProductInput {
  'imageRefs' : Array<string>,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'category' : Category,
  'colors' : Array<string>,
  'price' : bigint,
  'careInstructions' : string,
}
export interface ShippingAddress {
  'street' : string,
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'state' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserAccount {
  'principal' : Principal,
  'savedAddresses' : Array<ShippingAddress>,
  'updatedAt' : Timestamp,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[ProductInput], Product>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'attachStripeSession' : ActorMethod<[OrderId, string], [] | [Order]>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[OrderInput], Order>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'filterProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrdersByGuestEmail' : ActorMethod<[string], Array<Order>>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getSavedAddresses' : ActorMethod<[], Array<ShippingAddress>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'removeAddress' : ActorMethod<[bigint], boolean>,
  'saveAddress' : ActorMethod<[ShippingAddress], UserAccount>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [Order]>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], [] | [Product]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];