/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'Men' : IDL.Null,
  'Accessories' : IDL.Null,
  'Kids' : IDL.Null,
  'Women' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'imageRefs' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'category' : Category,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
  'careInstructions' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Product = IDL.Record({
  'id' : ProductId,
  'imageRefs' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'updatedAt' : Timestamp,
  'category' : Category,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
  'careInstructions' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const ShippingAddress = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'fullName' : IDL.Text,
  'state' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'color' : IDL.Text,
  'size' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'priceAtPurchase' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'guestEmail' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'userPrincipal' : IDL.Opt(IDL.Principal),
  'totalAmount' : IDL.Nat,
  'shippingAddress' : ShippingAddress,
  'items' : IDL.Vec(OrderItem),
  'stripeSessionId' : IDL.Opt(IDL.Text),
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const OrderInput = IDL.Record({
  'guestEmail' : IDL.Opt(IDL.Text),
  'shippingAddress' : ShippingAddress,
  'items' : IDL.Vec(OrderItem),
});
export const ProductFilter = IDL.Record({
  'color' : IDL.Opt(IDL.Text),
  'size' : IDL.Opt(IDL.Text),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'searchTerm' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
  'minPrice' : IDL.Opt(IDL.Nat),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const UserAccount = IDL.Record({
  'principal' : IDL.Principal,
  'savedAddresses' : IDL.Vec(ShippingAddress),
  'updatedAt' : Timestamp,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addProduct' : IDL.Func([ProductInput], [Product], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attachStripeSession' : IDL.Func([OrderId, IDL.Text], [IDL.Opt(Order)], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func([OrderInput], [Order], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'filterProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getOrdersByGuestEmail' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getSavedAddresses' : IDL.Func([], [IDL.Vec(ShippingAddress)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'removeAddress' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveAddress' : IDL.Func([ShippingAddress], [UserAccount], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Opt(Order)], []),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Opt(Product)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'Men' : IDL.Null,
    'Accessories' : IDL.Null,
    'Kids' : IDL.Null,
    'Women' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'imageRefs' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'category' : Category,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
    'careInstructions' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Product = IDL.Record({
    'id' : ProductId,
    'imageRefs' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'updatedAt' : Timestamp,
    'category' : Category,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
    'careInstructions' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const ShippingAddress = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'fullName' : IDL.Text,
    'state' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'color' : IDL.Text,
    'size' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'priceAtPurchase' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'createdAt' : Timestamp,
    'guestEmail' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'userPrincipal' : IDL.Opt(IDL.Principal),
    'totalAmount' : IDL.Nat,
    'shippingAddress' : ShippingAddress,
    'items' : IDL.Vec(OrderItem),
    'stripeSessionId' : IDL.Opt(IDL.Text),
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const OrderInput = IDL.Record({
    'guestEmail' : IDL.Opt(IDL.Text),
    'shippingAddress' : ShippingAddress,
    'items' : IDL.Vec(OrderItem),
  });
  const ProductFilter = IDL.Record({
    'color' : IDL.Opt(IDL.Text),
    'size' : IDL.Opt(IDL.Text),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'searchTerm' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
    'minPrice' : IDL.Opt(IDL.Nat),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const UserAccount = IDL.Record({
    'principal' : IDL.Principal,
    'savedAddresses' : IDL.Vec(ShippingAddress),
    'updatedAt' : Timestamp,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addProduct' : IDL.Func([ProductInput], [Product], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attachStripeSession' : IDL.Func([OrderId, IDL.Text], [IDL.Opt(Order)], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func([OrderInput], [Order], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'filterProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getOrdersByGuestEmail' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getSavedAddresses' : IDL.Func([], [IDL.Vec(ShippingAddress)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'removeAddress' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveAddress' : IDL.Func([ShippingAddress], [UserAccount], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Opt(Order)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, ProductInput],
        [IDL.Opt(Product)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };